Repository tensorflow/serving, pull requests merged in 2018-12, with the labels that each got.

#1205 Need space after curl `filename`
  tensorflow_serving/g3doc/serving_kubernetes.md
Labels: cla: yes

#1212 Update the tutorial code snippet to match the latest mnist_saved_model.py
  tensorflow_serving/g3doc/serving_basic.md
Labels: cla: yes

#1213 Update run_in_docker.sh
  tools/run_in_docker.sh
Labels: cla: yes

#1218 Update api_rest.md
  tensorflow_serving/g3doc/api_rest.md
Labels: cla: yes

#1220 Update README.md
  tensorflow_serving/batching/README.md
Labels: cla: yes, kokoro:force-run

#1180 Fix default path of metrics endpoint
  tensorflow_serving/model_servers/http_server.cc
Labels: cla: yes, stat:awaiting response
