Repository tensorflow/serving, pull requests merged in 2018-06, with the labels that each got.

#907 Bump patch level to release recompiled binaries.
  tensorflow_serving/model_servers/BUILD
Labels: cla: yes

#908 Bump patch level to release recompiled binaries.
  tensorflow_serving/model_servers/BUILD
Labels: cla: yes

#913 **Upstream changes from internal**
  WORKSPACE
  tensorflow_serving/g3doc/api_rest.md
  tensorflow_serving/model_servers/http_server.cc
  tensorflow_serving/model_servers/http_server.h
  tensorflow_serving/tools/docker/Dockerfile.devel
  tensorflow_serving/tools/docker/Dockerfile.devel-gpu
  tensorflow_serving/util/fast_read_dynamic_ptr.h
  tensorflow_serving/util/net_http/client/BUILD
  tensorflow_serving/util/net_http/client/evhttp_connection.cc
  tensorflow_serving/util/net_http/client/evhttp_connection.h
  tensorflow_serving/util/net_http/client/testing/evhttp_echo_client.cc
  tensorflow_serving/util/net_http/server/internal/BUILD
  tensorflow_serving/util/net_http/server/internal/evhttp_request.h
  tensorflow_serving/util/net_http/server/internal/evhttp_request_test.cc
  tensorflow_serving/util/net_http/server/internal/evhttp_server.cc
  tensorflow_serving/util/net_http/server/internal/evhttp_server.h
  tensorflow_serving/util/net_http/server/internal/evhttp_server_test.cc
  tensorflow_serving/util/net_http/server/internal/server_support.h
  tensorflow_serving/util/net_http/server/public/BUILD
  tensorflow_serving/util/net_http/server/public/httpserver.h
  tensorflow_serving/util/net_http/server/public/httpserver_interface.h
  tensorflow_serving/util/net_http/server/public/server_request_interface.h
  tensorflow_serving/util/net_http/server/testing/evhttp_echo_server.cc
Labels: cla: yes

#917 Release 1.8.0 TF Serving based on TensorFlow 1.8.0
  WORKSPACE
  tensorflow_serving/core/aspired_versions_manager.cc
  tensorflow_serving/core/aspired_versions_manager_test.cc
  tensorflow_serving/core/dynamic_source_router.h
  tensorflow_serving/model_servers/BUILD
  tensorflow_serving/tools/pip_package/setup.py
  tensorflow_serving/workspace.bzl
Labels: cla: yes, kokoro:force-run

#922 fix version for dependencies
  tensorflow_serving/tools/pip_package/setup.py
Labels: cla: yes

#932 **Upstream changes from internal**
  WORKSPACE
  tensorflow_serving/apis/model.proto
  tensorflow_serving/example/BUILD
  tensorflow_serving/example/inception_client.cc
  tensorflow_serving/g3doc/docker.md
  tensorflow_serving/g3doc/leftnav_files
  tensorflow_serving/model_servers/BUILD
  tensorflow_serving/model_servers/grpc_status_util.cc
  tensorflow_serving/model_servers/grpc_status_util.h
  tensorflow_serving/model_servers/main.cc
  tensorflow_serving/model_servers/model_service_impl.h
  tensorflow_serving/tools/docker/Dockerfile
  tensorflow_serving/tools/docker/Dockerfile.devel
  tensorflow_serving/tools/docker/Dockerfile.devel-gpu
Labels: cla: yes

#934 **Upstream changes from internal**
  WORKSPACE
  tensorflow_serving/g3doc/api_rest.md
  tensorflow_serving/g3doc/serving_inception.md
  tensorflow_serving/g3doc/setup.md
Labels: cla: yes

#943 Update documentation to add OOM workaround building in docker image
  tensorflow_serving/g3doc/docker.md
Labels: cla: yes, ready to pull

#950 Update pip version.
  tensorflow_serving/tools/pip_package/setup.py
Labels: cla: yes

#949 Fix a compilation error with old gcc compiler
  tensorflow_serving/model_servers/http_rest_prediction_handler_test.cc
Labels: cla: yes, ready to pull

#965 Update version for 1.7.1 release.
  WORKSPACE
  tensorflow_serving/tools/pip_package/setup.py
Labels: cla: yes
